name: Build Wheels
on:
  push:
    branches:
      - "*"
jobs:
  manylinux:
    strategy:
      fail-fast: false
      matrix:
        target:
          - manylinux-x86_64
          - manylinux-aarch64
          
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
      - uses: actions/checkout@v3
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Enable buildkit cache
        uses: actions/cache@v2
        with:
          path: /tmp/buildkit-cache/buildkit-state.tar
          key: ${{ runner.os }}-buildkit-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildkit-
      
      - name: Load buildkit state from cache
        uses: dashevo/gh-action-cache-buildkit-state@v1
        with:
          builder: buildx_buildkit_${{ steps.buildx.outputs.name }}0
          cache-path: /tmp/buildkit-cache

      - name: Bake
        run: docker buildx bake ${{ matrix.target }}
