name: Build Wheels

concurrency: ${{ github.workflow }}

on:
  push:
    branches:
      - "*"

  release:
    types:
      - published

jobs:
  manylinux:
    strategy:
      fail-fast: false
      matrix:
        arch:
          - x86_64
          - aarch64
        version:
          - "310"
          - "39"
          - "38"
          - "37"

    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}

    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true

      - name: Login to Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Restore/save CCache
        uses: actions/cache@v3
        with:
          path: ./output/ccache
          key: ccache-${{ runner.os }}-manylinux-${{ matrix.arch }}-${{ matrix.version }}-${{ github.sha }}-${{ github.run_attempt }}
          restore-keys: |
            ccache-${{ runner.os }}-manylinux-${{ matrix.arch }}-${{ matrix.version }}-${{ github.sha }}
            ccache-${{ runner.os }}-manylinux-${{ matrix.arch }}-${{ matrix.version }}
            ccache-${{ runner.os }}-manylinux-${{ matrix.arch }}
            ccache-${{ runner.os }}-manylinux
            ccache-${{ runner.os }}
            ccache-

      - name: Bake
        env:
          CACHE_TO_IMAGE: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          CACHE_TAG_PREFIX: cache-
          CCACHE: ./output/ccache
        run: |
          mkdir -p ./output/ccache
          docker buildx bake ${{ matrix.version }}-manylinux-${{ matrix.arch }}

      - name: Add wheels as build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: wheels
          path: ./output/wheelhouse/*.whl

      - name: Add wheels to release
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v1
        with:
          files: ./output/wheelhouse/*.whl

