name: Build Wheels

concurrency: ${{ github.workflow }}

on:
  push:
    branches:
      - "*"

  release:
    types:
      - published

jobs:
  manylinux:
    strategy:
      fail-fast: false
      matrix:
        target:
          - manylinux-x86_64
          - manylinux-aarch64

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}

    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true

      - name: Login to Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Bake
        env:
          CACHE_IMAGE: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:cache-${{ matrix.target }}
        run: docker buildx bake ${{ matrix.target }}

      - name: Add wheels as build artifacts
        uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl

      - name: Add wheels to release
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v1
        with:
          files: ./wheelhouse/*.whl

