name: Build Wheels

concurrency: ${{ github.workflow }}

on:
  push:
    branches:
      - "*"
  
  release:
    types:
      - published
  
jobs:
  manylinux:
    strategy:
      fail-fast: false
      matrix:
        target:
          - manylinux-x86_64
          - manylinux-aarch64
          
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true
        
      - name: Enable buildkit cache
        uses: jashandeep-sohi/cache@31e100c3910cca70aeab409babf9ee1889ef1e1c
        env:
          FORCE_SAVE_CACHE: "true"
        with:
          path: /tmp/buildkit-cache/buildkit-state.tar
          key: buildkit-${{ runner.os }}-${{ matrix.target }}-${{ github.sha }}-${{ github.run_attempt }}
          restore-keys: |
            buildkit-${{ runner.os }}-${{ matrix.target }}-${{ github.sha }}-
            buildkit-${{ runner.os }}-${{ matrix.target }}-
            buildkit-${{ runner.os }}-
      
      - name: Load buildkit state from cache
        uses: dashevo/gh-action-cache-buildkit-state@v1
        with:
          builder: buildx_buildkit_${{ steps.buildx.outputs.name }}0
          cache-path: /tmp/buildkit-cache
          cache-max-size: 5g

      - name: Bake
        run: docker buildx bake ${{ matrix.target }}
        
      - name: Add wheels as build artifacts
        uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
      
      - name: Add wheels to release
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v1
        with:
          files: ./wheelhouse/*.whl
    
